#!/usr/bin/env python3
"""
Generate LICENSING.md and NOTICES.txt from sources/registry.json.

Two documents, because they answer different questions:

  LICENSING.md  why the aggregate may carry the licence it carries. The
                per-source licence map already existed in SOURCES.md; what was
                missing was the analysis of the SET. Licences are individually
                fine and collectively contradictory all the time, and a
                compilation is governed by the combination, not by the rows.

  NOTICES.txt   the attribution that has to TRAVEL WITH THE FILE. SOURCES.md
                lives in the repository, but MIT and Apache-2.0 require their
                notice to accompany the distributed work, and someone who
                downloads blacklist.txt from a release never sees the repository.
                This file is published as a release asset for that reason.

Both are generated so they cannot drift from the registry the pipeline actually
uses - a stale attribution map is a licensing problem, not a documentation nit.

Run: python3 scripts/generate_licensing.py [--check]
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path
from typing import Dict, List

REGISTRY = Path('sources/registry.json')
LICENSING = Path('LICENSING.md')
NOTICES = Path('NOTICES.txt')


def effective_license(entry: Dict) -> str:
    """The licence actually relied on, after any dual-licence election."""
    license = entry['license']
    return license.get('elected') or license.get('spdx') or license.get('name') or 'not stated'


def build_licensing(registry: Dict) -> str:
    sources = registry['sources']
    aggregate = registry.get('aggregate_license', 'not declared')

    families = Counter(effective_license(e) for e in sources)
    pending = [e for e in sources
               if (e['license'].get('gpl3_compatibility') or {}).get('status') == 'pending']
    settled = [e for e in sources if e not in pending]

    # One row per licence family, with the reason that family may be
    # incorporated. Taken from the registry so the published reasoning and the
    # enforced check cannot disagree.
    seen: Dict[str, str] = {}
    for entry in sources:
        compat = entry['license'].get('gpl3_compatibility') or {}
        if compat.get('status') == 'compatible':
            seen.setdefault(effective_license(entry), compat.get('rationale', ''))

    rows = '\n'.join(
        f'| `{name}` | {families[name]} | {reason} |'
        for name, reason in sorted(seen.items())
    )

    pending_rows = '\n'.join(
        f'| `{e["id"]}` | {e["name"]} | {e["license"].get("name")} | '
        f'{(e["license"].get("gpl3_compatibility") or {}).get("rationale", "")} |'
        for e in pending
    )

    elected = [e for e in sources if e['license'].get('elected')]
    elected_rows = '\n'.join(
        f'| `{e["id"]}` | {e["license"]["spdx"]} | **{e["license"]["elected"]}** |'
        for e in elected
    )

    # Derived, not written down: the count that forces "-only" rather than
    # "-or-later" is the whole reason for the suffix, and a hardcoded number in
    # a generated file is wrong the first time a source is added or dropped.
    gpl_only = sum(1 for e in sources if effective_license(e) == 'GPL-3.0-only')

    return f"""# Licensing of the published blacklist

<!-- Generated by scripts/generate_licensing.py from sources/registry.json.
     Do not edit by hand: edit the registry and regenerate. -->

**The published `blacklist.txt`, and the `rpz_blacklist.txt` and
`unbound_blacklist.txt` derived from it, are distributed under
`{aggregate}`.**

This document explains why that is the correct licence and how each upstream
source reaches it. The per-source licence map is in [SOURCES.md](SOURCES.md);
the attribution that travels with the released files is in
[NOTICES.txt](NOTICES.txt).

## Why the aggregate is a combined work, not a mere aggregation

The GPL's "mere aggregation" clause covers **separate and independent** works
distributed together on one medium - the way a Linux distribution image carries
many programs that each remain a distinct, extractable file.

That is not what this project produces. `generate.sh` concatenates every source
and runs `sort -u`, then sanitisation and whitelisting. The result is:

- **one file**, not a container of files;
- **deduplicated**, which irreversibly destroys the record of which source
  supplied which domain;
- **editorially transformed** relative to every input.

No individual upstream list can be extracted from the output. `source_stats.py`
exists precisely because attribution has to be **reconstructed** afterwards by
comparing the raw downloads against the result - which would be unnecessary if
the works were still separate inside it.

So the compilation is governed by the combination of its inputs' licences, and
every input must be compatible with the licence the whole carries.

## Why the earlier position could not stand

Previous versions of the README stated that the output was "not covered by" the
GPL and that each list remained "under its own license". In one merged,
deduplicated file no line can be matched to its own licence any more, so that
position described something the artifact cannot do.

It was also inconsistent with the project's own conduct. Five feeds were
**excluded for licensing reasons** - StopForumSpam, red.flag.domains,
phishing.army, RPiList and CERT Polska, all carrying non-commercial or
no-derivatives clauses (see `removed_sources` in the registry). That exclusion
only makes sense if upstream licences govern the aggregate. If they did not, the
NC clauses would have been irrelevant and those feeds could have been included.

## Why `{aggregate}` specifically

`GPL-3.0-only`, not `-or-later`: {gpl_only} of the sources are themselves
`GPL-3.0-only`, which withholds the later-version option, so the combined work
cannot offer it either.

| Effective licence | Sources | Why it can be incorporated |
|---|---|---|
{rows}

{settled and f'**{len(settled)} of {len(sources)} sources** are settled on this basis.' or ''}

### Dual-licensed sources: the branch elected

A dual-licensed source is only usable once a branch is chosen, and an unrecorded
choice cannot be audited. The election is stored in the registry as
`license.elected`.

| Source | Offered as | Elected |
|---|---|---|
{elected_rows or '| - | - | - |'}

### Not yet settled

These are **open questions, not conclusions**. They are recorded here rather
than assumed, because a licence claim that nobody can check is worth nothing.

| Source | List | Licence | What is open |
|---|---|---|---|
{pending_rows or '| - | - | - | none |'}

## What this means if you redistribute

Using the list - loading it into Pi-hole, AdGuard Home, Unbound or BIND - is not
distribution and imposes nothing on you.

If you **redistribute** the list, or a work derived from it, `{aggregate}`
applies: keep the licence and copyright notices, pass on the same licence, and
make the corresponding source available. Ship
[NOTICES.txt](NOTICES.txt) with it - that is the upstream attribution.

If you need a copy without copyleft obligations, this project does not currently
publish one. Open an issue if that would be useful.

## Rights holders

If you maintain one of these lists and want it changed or removed, open an issue
and it will be removed. No argument, no delay.

## Standing of this document

This is a compliance record, not legal advice. It states which licences apply,
where each was verified, and the reasoning connecting them - so that the claim
can be checked rather than taken on trust. It has not been reviewed by counsel.
"""


def build_notices(registry: Dict) -> str:
    sources = sorted(registry['sources'], key=lambda e: e['name'].lower())
    aggregate = registry.get('aggregate_license', 'not declared')

    blocks: List[str] = []
    for entry in sources:
        license = entry['license']
        lines = [
            f"{entry['name']}",
            f"    Project     : {entry['project']}",
            f"    Attribution : {entry['maintainer']}",
            f"    Homepage    : {entry['homepage']}",
            f"    Licence     : {effective_license(entry)}",
        ]
        if license.get('elected'):
            lines.append(f"    Offered as  : {license['spdx']} (this project elects "
                         f"{license['elected']})")
        if license.get('url'):
            lines.append(f"    Licence text: {license['url']}")
        if license.get('copyright'):
            lines.append(f"    Copyright   : {license['copyright']}")
        if entry.get('mirror_of'):
            lines.append(f"    Fetched via : {entry['mirror_of']['name']} "
                         f"({entry['mirror_of']['url']}) - a re-publisher, not the author")
        if entry.get('first_party'):
            lines.append("    Note        : maintained in this repository, not a third-party list")
        blocks.append('\n'.join(lines))

    recorded = sum(1 for e in sources if e['license'].get('copyright'))

    return f"""NOTICES
=======

The blacklist distributed with this file is an aggregate of {len(sources)} domain
lists produced by other people. It is published under {aggregate}; see
LICENSING.md in the project repository for why.

Every list below is redistributed under the licence named against it. This file
exists so that the attribution travels with the released artifact: MIT and
Apache-2.0 require their notice to accompany the work, and someone who downloads
a release asset never sees the repository.

The authoritative licence text for each entry is at the URL given. Where a
verbatim upstream copyright line has been recorded it is reproduced; at the time
of writing {recorded} of {len(sources)} entries carry one, and the remainder name the
maintainer and link to the licence instead. Closing that gap is tracked in the
project's issues.

Project repository: https://github.com/fabriziosalmi/blacklists
Full licence map  : https://github.com/fabriziosalmi/blacklists/blob/main/SOURCES.md

-------------------------------------------------------------------------------

{chr(10).join(blocks)}

-------------------------------------------------------------------------------

If you hold rights in any list above and want it changed or removed, open an
issue at https://github.com/fabriziosalmi/blacklists/issues and it will be
removed.
"""


def main() -> int:
    parser = argparse.ArgumentParser(description='Generate LICENSING.md and NOTICES.txt')
    parser.add_argument('--check', action='store_true',
                        help='Fail if the generated files are out of date')
    args = parser.parse_args()

    if not REGISTRY.exists():
        print(f'FAIL: {REGISTRY} not found', file=sys.stderr)
        return 1

    registry = json.loads(REGISTRY.read_text(encoding='utf-8'))
    wanted = {LICENSING: build_licensing(registry), NOTICES: build_notices(registry)}

    if args.check:
        stale = [str(path) for path, content in wanted.items()
                 if (path.read_text(encoding='utf-8') if path.exists() else '') != content]
        if stale:
            print(f'FAIL: out of date: {", ".join(stale)}. Run: '
                  f'python3 scripts/generate_licensing.py', file=sys.stderr)
            return 1
        print(f'OK: {LICENSING} and {NOTICES} are up to date')
        return 0

    for path, content in wanted.items():
        path.write_text(content, encoding='utf-8')
    print(f'✓ Wrote {LICENSING} and {NOTICES}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
