#!/usr/bin/env python3
"""
Generate SOURCES.md from sources/registry.json.

SOURCES.md is the human-readable attribution and licence map for the aggregated
blacklist. It is generated rather than hand-maintained so that it cannot drift
away from the registry the pipeline and the website actually use - a stale
attribution table is a licensing problem, not a documentation nit.

The prose below is hand-written and preserved verbatim; only the tables are
derived from the registry.

Run: python3 scripts/generate_sources_md.py [--check]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List

REGISTRY = Path('sources/registry.json')
OUTPUT = Path('SOURCES.md')

PREAMBLE = """# Sources and Licenses

<!-- Generated by scripts/generate_sources_md.py from sources/registry.json.
     Do not edit the tables by hand: edit the registry and regenerate. -->

This project is an **aggregator**. The published `blacklist.txt` (and the
derived `rpz_blacklist.txt` and `unbound_blacklist.txt`) is a compilation of
domain lists produced by third parties. Each upstream list remains the property
of its authors and is redistributed here **under its own license and terms**,
listed below.

The aggregation tooling in this repository (`generate.py`, `generate.sh`,
`sanitize.py`, `whitelist.py`, `check_whitelist.py`, and the helper scripts) is
licensed under **GPL-3.0** (see [`LICENSE`](LICENSE) and the License section of
the [README](README.md)). That license covers the code, **not** the aggregated
data, which stays under the licenses on this page.

The list of upstream feeds is maintained in
[`blacklists.fqdn.urls`](blacklists.fqdn.urls). If you are a rights holder and
want a change or removal, please open an issue.

Every license below is recorded only when it was confirmed against an
authoritative source - the upstream repository's license file, the project's own
license page, or the list's own header - and the **Evidence** column links to
what was checked. Where no license statement could be found, the row says so
instead of guessing.

Attribution key:
- **Permissive** (MIT / Apache-2.0 / BSD / custom permissive): keep the
  copyright and license notice.
- **Copyleft** (GPL-3.0 / MPL-2.0): keep copyright and license, preserve the
  same license on redistribution, keep the source available.
- **Share-alike** (CC BY-SA / CC BY): give credit and redistribute under the
  same license.
- **Public domain** (CC0 / Unlicense / PD): no attribution legally required
  (credit still given here as a courtesy).

---
"""

MIRRORS_NOTE = """
## Notes on mirrors

Some lists are fetched through **firebog** (`https://v.firebog.net`), which is a
mirror/index, not the original author. The rows above attribute those lists to
their **upstream** authors (AdGuard, EasyList, UT1 Toulouse), which is where the
license and credit are owed.
"""

FOOTER = """
---

*This file is generated from [`sources/registry.json`](sources/registry.json).
Per-source fetch status and contribution figures are published at
<https://fabriziosalmi.github.io/blacklists/#sources>.*
"""

# Which section each license family belongs to, in output order.
SECTIONS: List[tuple] = [
    ('Permissive (attribution required)',
     ('MIT', 'Apache-2.0', 'BSD-2-Clause', 'BSD-3-Clause')),
    ('Copyleft (preserve license + attribution)',
     ('GPL-3.0-only', 'GPL-3.0-or-later', 'MPL-2.0', 'AGPL-3.0-only')),
    ('Share-alike (attribution + share-alike)',
     ('CC-BY-SA-4.0', 'CC-BY-SA-3.0', 'CC-BY-4.0',
      'GPL-3.0-or-later OR CC-BY-SA-3.0')),
    ('Public domain (free to use)',
     ('CC0-1.0', 'Unlicense')),
]

ATTRIBUTION = {
    'MIT': 'Keep notice',
    'Apache-2.0': 'Keep notice + NOTICE',
    'GPL-3.0-only': 'Credit + GPL-3.0 + source',
    'GPL-3.0-or-later': 'Credit + GPL-3.0 + source',
    'MPL-2.0': 'Credit + MPL-2.0 + source',
    'CC-BY-SA-4.0': 'Credit + same license',
    'CC-BY-SA-3.0': 'Credit + same license',
    'GPL-3.0-or-later OR CC-BY-SA-3.0': 'Credit + same license',
    'CC0-1.0': 'Not required',
    'Unlicense': 'Not required',
}


def escape(text: str) -> str:
    """Keep table cells from breaking the Markdown table."""
    return (text or '').replace('|', r'\|')


def group_key(entry: Dict) -> str:
    license = entry['license']
    if not license.get('verified'):
        return 'unverified'
    spdx = license.get('spdx')
    if not spdx:
        return 'custom'
    for title, spdx_ids in SECTIONS:
        if spdx in spdx_ids:
            return title
    return 'custom'


def render_row(entry: Dict) -> str:
    license = entry['license']
    upstream = f"{escape(entry['maintainer'])} - {entry['homepage']}"
    if entry.get('mirror_of'):
        upstream += f" (via {escape(entry['mirror_of']['name'])})"

    label = escape(license.get('spdx') or license.get('name') or 'Not stated')
    evidence = f"[{license['evidence']}]({license['url']})" if license.get('url') else '-'
    attribution = ATTRIBUTION.get(license.get('spdx'), 'Credit')

    return (f"| {escape(entry['name'])} | {upstream} | {label} | "
            f"{attribution} | {evidence} |")


def render_table(entries: List[Dict]) -> str:
    header = ('| List | Upstream (owner / URL) | License | Attribution | Evidence |\n'
              '|---|---|---|---|---|\n')
    return header + '\n'.join(render_row(e) for e in entries) + '\n'


def build(registry: Dict) -> str:
    sources = registry['sources']
    grouped: Dict[str, List[Dict]] = {}
    for entry in sources:
        grouped.setdefault(group_key(entry), []).append(entry)

    parts = [PREAMBLE]

    for title, _ in SECTIONS:
        entries = grouped.get(title)
        if entries:
            parts.append(f'\n## {title}\n\n{render_table(entries)}')

    if grouped.get('custom'):
        parts.append(
            '\n## Custom terms (no standard SPDX identifier)\n\n'
            'These sources publish terms that do not map to a standard license '
            'identifier. The evidence link is the exact text that was read.\n\n'
            + render_table(grouped['custom'])
        )

    if grouped.get('unverified'):
        parts.append(
            '\n## No license statement found\n\n'
            '**These sources publish no license terms that could be located.** '
            'They are redistributed on the basis that they are published as '
            'public threat-intelligence feeds, but that is an assumption, not a '
            'grant. Rights holders should open an issue and the feed will be '
            'removed on request.\n\n'
            + render_table(grouped['unverified'])
        )
        notes = [(e['name'], e['license']['note'])
                 for e in grouped['unverified'] if e['license'].get('note')]
        if notes:
            parts.append('\n' + '\n'.join(
                f'- **{escape(name)}**: {escape(note)}' for name, note in notes
            ) + '\n')

    parts.append(MIRRORS_NOTE)

    removed = registry.get('removed_sources') or []
    if removed:
        parts.append(
            '\n## Removed for licensing or availability\n\n'
            'The following feeds are deliberately **not** fetched:\n\n'
            '| Feed | Reason | Terms | Detail |\n|---|---|---|---|\n'
            + '\n'.join(
                f"| [{escape(r['name'])}]({r['homepage']}) | {r['reason']} | "
                f"{escape(r.get('license') or '-')} | {escape(r['detail'])} |"
                for r in removed
            ) + '\n'
        )

    parts.append(FOOTER)
    return ''.join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description='Generate SOURCES.md')
    parser.add_argument('--check', action='store_true',
                        help='Fail if SOURCES.md is out of date instead of rewriting it')
    args = parser.parse_args()

    if not REGISTRY.exists():
        print(f'FAIL: {REGISTRY} not found', file=sys.stderr)
        return 1

    content = build(json.loads(REGISTRY.read_text(encoding='utf-8')))

    if args.check:
        current = OUTPUT.read_text(encoding='utf-8') if OUTPUT.exists() else ''
        if current != content:
            print(f'FAIL: {OUTPUT} is out of date. Run: '
                  f'python3 scripts/generate_sources_md.py', file=sys.stderr)
            return 1
        print(f'OK: {OUTPUT} is up to date')
        return 0

    OUTPUT.write_text(content, encoding='utf-8')
    print(f'✓ Wrote {OUTPUT}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
