name: Create Unbound Blacklist

on:
  workflow_run:
    workflows: ["Generate the blacklist"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Download blacklist
      run: |
        wget https://github.com/fabriziosalmi/blacklists/releases/download/latest/blacklist.txt

    - name: Process for Unbound
      run: |
        echo "# Unbound blacklist format" > unbound_blacklist.txt
        while IFS= read -r domain
        do
          echo "local-zone: \"$domain\" static" >> unbound_blacklist.txt
        done < blacklist.txt

    - name: Create a Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          unbound_blacklist.txt
        tag_name: latest #
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
