name: Create RPZ Blacklist

on:
  workflow_run:
    workflows: ["Generate the blacklist"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Download blacklist
      run: |
        wget https://github.com/fabriziosalmi/blacklists/releases/download/latest/blacklist.txt
        cat blacklist.txt | while read line; do echo "$line CNAME ."; done > rpz_blacklist.txt

    - name: Create a Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          rpz_blacklist.txt
        tag_name: latest
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

