name: Blacklist Stats

on:
  schedule:
    - cron: '10 * * * *'  # Run every hour
  workflow_dispatch: # allows to manually trigger the workflow

jobs:
  generate_stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Fetch the last 2 commits instead of just the latest

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run blacklist stats script
        id: run_stats
        run: python3 stats.py

      - name: Commit and push stats.md
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Update stats.md"
          add: "stats.md"
        
      - name: Create or update the stats comment
        uses: peter-evans/create-or-update-comment@v4
        with:
           issue-number: 1 # Replace with the actual issue number if needed
           body: |
             ${{ steps.run_stats.outputs.stats_output }}
